services:
  blade:
    image: blade_image
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace/app
    working_dir: /workspace/app
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    stdin_open: true
    tty: true
