smote_data_dir: "data/ton_iot/SMOTENC_train_data_bak"
models_to_train_config:
  "tf_mlp":
      epochs: 40
      batch_size: 5120
      learning_rate: 3e-3
  "xgb": {}
  "rf": {}

use_categorical_embedding: true
poison_fraction: 0.1

